version: '3'

services:

    nginx:
        restart: always
        build:
            context: ./docker/nginx/
            dockerfile: dockerfile
        volumes:
            - ./frontend:/frontend
        ports:
            - "8085:80"
            - "8086:81"
        environment:
           - NGINX_PORT=80

    mysql:
        restart: always
        volumes:
            - ./backend/temp/mysql_data:/var/lib/mysql
        build:
            context: ./docker/mysql
            dockerfile: dockerfile
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
        ports:
            - "5998:3306"

    python:
        restart: always
        build:
            context: ./docker/python/
            dockerfile: dockerfile
        command: bash start.sh
        volumes:
            - ./backend/product:/product
        env_file:
            - ./backend/envs/env.env
            - ./backend/envs/mysql.env
        depends_on:
            - mysql

    angular:
        restart: always
        build:
            context: ./docker/angular
            dockerfile: dockerfile
        command: bash start.sh
        container_name: angular
        volumes:
            - ./frontend:/frontend
            - volume-node-modules:/frontend/node_modules

volumes:
    volume-node-modules:
