version: '3'

services:
    
    python:
        restart: always
        build:
            context: ./docker/python/
            dockerfile: dockerfile
        command: bash start.sh
        volumes:
            - ./product:/product
        ports:
            - "4999:5000"
        env_file:
            - ./envs/env.env
            - ./envs/mysql.env
    
    mysql:
        restart: always
        volumes:
            - ./temp/mysql_data:/var/lib/mysql
        build:
            context: ./docker/mysql
            dockerfile: dockerfile
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
        ports:
            - "4998:3306"
            