version: '3'

services:

    mysql:
        restart: always
        volumes:
            - ./backend/temp/mysql_data:/var/lib/mysql
        build:
            context: ./docker/mysql
            dockerfile: dockerfile
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
        ports:
            - "5998:3306"

    python:
        restart: always
        build:
            context: ./docker/python/
            dockerfile: dockerfile
        command: bash start.sh
        volumes:
            - ./backend/product:/product
        ports:
            - "5999:5000"
        env_file:
            - ./backend/envs/env.env
            - ./backend/envs/mysql.env
        depends_on:
            - mysql

    angular:
        restart: always
        build:
            context: ./docker/angular
            dockerfile: dockerfile
        ports:
            - "4201:4200"
        container_name: angular
        volumes:
            - ./frontend:/frontend