version: '3'

services:

    mysql:
        volumes:
            - /mysql_data/mysql:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: ",w?kt;V_6,XznDU:M*;:cm~/XBrm2e"
    
    python:
        env_file:
            - ./backend/envs/prod/env.env
            - ./backend/envs/prod/mysql.env
