version: '3'

services:

    mysql:
        volumes:
            - /mysql_data/mysql:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "1w8kt5V_67XznDU4M237cm52XBrm2e"
    
    python:
        env_file:
            - ./backend/envs/prod/env.env
            - ./backend/envs/prod/mysql.env
