FROM node:19.4.0

ENV NODE_PATH=/usr/local/lib/node_modules
ENV GENERATE_SOURCEMAP=false
ENV NODE_OPTIONS=--max-old-space-size=16384

WORKDIR /frontend

RUN npm install -g @angular/cli@15.1.4

RUN npm install -g @angular/animations@^15.0.0
RUN npm install -g @angular/cdk@github:angular/cdk-builds
RUN npm install -g @angular/cli@^15.1.4
RUN npm install -g @angular/common@^15.0.0
RUN npm install -g @angular/core@^15.0.0
RUN npm install -g @angular/forms@^15.0.0
RUN npm install -g @angular/material@github:angular/material2-builds
RUN npm install -g @angular/platform-browser-dynamic@^15.0.0
RUN npm install -g @angular/platform-browser@^15.0.0
RUN npm install -g @angular/router@^15.0.0
RUN npm install -g @material/animation@14.0.0
RUN npm install -g @material/base@14.0.0
RUN npm install -g @material/dom@14.0.0
RUN npm install -g @material/elevation@14.0.0
RUN npm install -g @material/feature-targeting@14.0.0
RUN npm install -g @material/rtl@14.0.0
RUN npm install -g @material/shape@14.0.0
RUN npm install -g @material/textfield@^15.0.0
RUN npm install -g @material/theme@14.0.0
RUN npm install -g @material/tooltip@14.0.0
RUN npm install -g @material/typography@14.0.0
RUN npm install -g @angular-devkit/build-angular@15.0.4
RUN npm install -g @angular/animations@^15.0.0
RUN npm install -g @angular/cdk@github:angular/cdk-builds
RUN npm install -g @angular/cli@^15.1.4
RUN npm install -g @angular/common@^15.0.0
RUN npm install -g @angular/compiler-cli@15.0.4
RUN npm install -g @angular/compiler@15.0.4
RUN npm install -g @angular/core@^15.0.0
RUN npm install -g @angular/forms@^15.0.0
RUN npm install -g @angular/material@github:angular/material2-builds
RUN npm install -g @angular/platform-browser-dynamic@^15.0.0
RUN npm install -g @angular/platform-browser@^15.0.0
RUN npm install -g @angular/router@^15.0.0
RUN npm install -g @material/animation@14.0.0
RUN npm install -g @material/base@14.0.0
RUN npm install -g @material/dom@14.0.0
RUN npm install -g @material/elevation@14.0.0
RUN npm install -g @material/feature-targeting@14.0.0
RUN npm install -g @material/rtl@14.0.0
RUN npm install -g @material/shape@14.0.0
RUN npm install -g @material/textfield@^15.0.0-canary.684e33d25.0
RUN npm install -g @material/theme@14.0.0
RUN npm install -g @material/tooltip@14.0.0
RUN npm install -g @material/typography@14.0.0
RUN npm install -g @types/jasmine@4.3.1
RUN npm install -g jasmine-auto-spies@6.9.9
RUN npm install -g jasmine-core@4.5.0
RUN npm install -g karma-chrome-launcher@3.1.1
RUN npm install -g karma-coverage@2.2.0
RUN npm install -g karma-jasmine-html-reporter@2.0.0
RUN npm install -g karma-jasmine@5.1.0
RUN npm install -g karma@6.4.2
RUN npm install -g rxjs@7.8.1
RUN npm install -g tslib@2.4.1
RUN npm install -g typescript@4.8.4
RUN npm install -g zone.js@~0.12.0

WORKDIR /frontend

ENTRYPOINT ["npm","start"]

