FROM node:19.4.0

ENV NODE_PATH=/usr/local/lib/node_modules
ENV GENERATE_SOURCEMAP=false
ENV NODE_OPTIONS=--max-old-space-size=16384

WORKDIR /frontend

RUN npm install -g @angular/cli@15.1.4

RUN npm install -g @angular/animations@^15.0.0\
    @angular/cdk@github:angular/cdk-builds \
    @angular/cli@^15.1.4 \
    @angular/common@^15.0.0 \
    @angular/core@^15.0.0 \
    @angular/forms@^15.0.0 \
    @angular/material@github:angular/material2-builds \
    @angular/platform-browser-dynamic@^15.0.0 \
    @angular/platform-browser@^15.0.0 \
    @angular/router@^15.0.0 \
    @material/animation@14.0.0 \
    @material/base@14.0.0 \
    @material/dom@14.0.0 \
    @material/elevation@14.0.0 \
    @material/feature-targeting@14.0.0 \
    @material/rtl@14.0.0 \
    @material/shape@14.0.0 \
    @material/textfield@^15.0.0 \
    @material/theme@14.0.0 \
    @material/tooltip@14.0.0 \
    @material/typography@14.0.0 \
    @angular-devkit/build-angular@15.0.4 \
    @angular/animations@^15.0.0 \
    @angular/cdk@github:angular/cdk-builds \
    @angular/cli@^15.1.4 \
    @angular/common@^15.0.0 \
    @angular/compiler-cli@15.0.4 \
    @angular/compiler@15.0.4 \
    @angular/core@^15.0.0 \
    @angular/forms@^15.0.0 \
    @angular/material@github:angular/material2-builds \
    @angular/platform-browser-dynamic@^15.0.0 \
    @angular/platform-browser@^15.0.0 \
    @angular/router@^15.0.0 \
    @material/animation@14.0.0 \
    @material/base@14.0.0 \
    @material/dom@14.0.0 \
    @material/elevation@14.0.0 \
    @material/feature-targeting@14.0.0 \
    @material/rtl@14.0.0 \
    @material/shape@14.0.0 \
    @material/textfield@^15.0.0-canary.684e33d25.0 \
    @material/theme@14.0.0 \
    @material/tooltip@14.0.0 \
    @material/typography@14.0.0 \
    @types/jasmine@4.3.1 \
    jasmine-auto-spies@6.9.9 \
    jasmine-core@4.5.0 \
    karma-chrome-launcher@3.1.1 \
    karma-coverage@2.2.0 \
    karma-jasmine-html-reporter@2.0.0 \
    karma-jasmine@5.1.0 \
    karma@6.4.2 \
    rxjs@7.8.1 \
    tslib@2.4.1 \
    typescript@4.8.4 \
    zone.js@~0.12.0 

WORKDIR /frontend

ENTRYPOINT ["npm","start"]

